version: '3'
services:
  ### PHP-FPM Container
  php:
    build: ./image/php/
    #ports:
    #- "9000:9000"
    volumes:
      - ./www/lumen/:/var/www/html
    links:
      - mysql-dev
    networks:
      - gateway
      - db

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - gateway

  mysql-dev:
    image: mysql:5.5
    container_name: mysql5.5-dev
    environment:
      MYSQL_ROOT_PASSWORD: abcdefg
    volumes:
        - ./image/mysql/data/:/var/lib/mysql
    ports:
        - '3306:3306'
    networks:
        - db
networks:
  db:
    driver: bridge
  gateway:
    driver: bridge
