version: '3'
services:

  nodejs:
    build: ./image/nodejs/
    container_name: nodejs-apigatway
    volumes:
      - ./api-gateway/:/usr/src/app
    ports:
      - "8081:3000"
      - "3000:3000"
    command: tail -f /dev/null
    links:
      - php
    networks:
      - gateway
      - mongo_db

  mongo:
    container_name: nodejs-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo_db

  php: #should rename to auth service
    build: ./image/php/
    container_name: php
    volumes:
      - ./www/lumen/:/var/www/html
    links:
      - mysql-dev
    networks:
      - gateway
      - db

  stores-service:
    build: ./image/php/
    container_name: stores-service
    volumes:
      - ./www/stores-and-branches/:/var/www/html
    links:
      - mysql-dev
    networks:
      - gateway
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80 #auth service
      - 8082:8080 #stores service
    volumes:
      - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - stores-service
      - php
    networks:
      - gateway

  mysql-dev:
    image: mysql:5.5
    container_name: mysql5.5-dev
    environment:
      MYSQL_ROOT_PASSWORD: abcdefg
    volumes:
        - ./image/mysql/data/:/var/lib/mysql
    ports:
        - '3306:3306'
    networks:
        - db
networks:
  db:
    driver: bridge
  mongo_db:
    driver: bridge
  gateway:
    driver: bridge
