swagger: "2.0"
info:
  description: "stores & branches"
  version: "1.0.0"
  title: "stores & branches"
basePath: "/v1"
schemes:
- "https"
paths:
  '/stores/{storeId}':
    get:
      tags:
        - Stores
      summary: get a store by ID
      description: Returns a single store
      operationId: getStoreById
      produces:
        - application/json
      parameters:
        - name: storeId
          in: path
          description: ID of store to return
          required: true
          type: integer
          format: int64
        - name: include
          in: query
          description: branches want to include, children/descendant
          required: false
          type: string
          items:
            type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Store'
        '404':
          description: Store not found
    put:
      tags:
        - Stores
      summary: Update an existing store
      description: ''
      operationId: updateStore
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: storeId
          in: path
          description: ID of store to return
          required: true
          type: integer
          format: int64
        - name: body
          in: body
          description: store need to be updated
          required: true
          schema:
            $ref: '#/definitions/Store'
      responses:
        '200':
          description: Store updated
        '404':
          description: Store not found
        '422':
          description: Empty store name

    delete:
      tags:
        - Stores
      summary: Deletes a store
      description: ''
      operationId: deleteStore
      produces:
        - application/json
      parameters:
        - name: storeId
          in: path
          description: Store id to delete
          required: true
          type: integer
          format: int64
      responses:
        '404':
          description: store not found
        '204':
          description: delete successfully
  '/stores/{storeId}/branches':
    get:
      tags:
        - Branches
      summary: list child branches of given store
      description: list child branches of given store
      responses:
        200:
          description: OK
      parameters:
        - name: storeId
          in: path
          description: ''
          required: true
          type: integer
          format: int64
    post:
      tags:
        - Branches
      summary: link a store under main store as a branch
      description: link a store under main store as a branch, all descendants become main store's descendants
      consumes: 
        - multipart/form-data
      responses:
        200:
          description: OK
      parameters:
        - name: storeId
          in: path
          description: ''
          required: true
          type: integer
          format: int64
        - name: branchStoreId
          in: formData
          description: ''
          required: true
          type: integer
          format: int64

  /stores:
    get:
      tags:
        - Stores
      summary: Get all stores
      description: Get all stores
      operationId: getAllStore
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Store'
    post:
      tags:
        - 'Stores'
      summary: Create new store
      description: Create new store
      operationId: createStore
      produces:
        - application/json
      parameters:
      - in: "body"
        name: "body"
        description: "Created store object"
        required: true
        schema:
          $ref: "#/definitions/Store"
      responses:
        default:
          description: "successful operation"


definitions:
  Store:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      parent_store_id:
        type: "integer"
        format: "int64"
